name: Build

on:
  push:
    branches: "master"
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run tests
      run: mvn test --file pom.xml

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Perform build
        run: mvn --file pom.xml -DskipTests --batch-mode --update-snapshots package

      - name: Upload build folder
        uses: actions/upload-artifact@master
        with:
          name: release
          path: |
            ./target/**/*.jar
            ./target/classes/db
            ./target/classes/application.properties
